version: '3.8'

networks:
  rotten-network:
    driver: bridge

volumes:
  mongo-vol:

services:
  mongodb:
    image: mongo
    networks:
      - rotten-network
    ports:
      - 27017:27017
    volumes:
      - mongo-vol:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USER_NAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_USER_PWD}

  webApp:
    image: thinogueiras/rotten-potatoes:latest
    networks:
      - rotten-network
    ports:
      - 5000:5000
    depends_on:
      - mongodb
    environment:
      MONGODB_HOST: ${DATABASE_HOST}
      MONGODB_USERNAME: ${DATABASE_USER_NAME}
      MONGODB_PASSWORD: ${DATABASE_USER_PWD}